version: '3.7'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data

  app:
    build: 
      context: ./app
    container_name: app-fastapi
    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    depends_on:
      - redis
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - "redis"

volumes:
    redis_data:
